apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: redpandadata/console:v3.1.0
        env:
        - name: KAFKA_BROKERS
          value: example-kafka-cluster-kafka-bootstrap:9092
          # value: kafka-proxy:29092
        ports:
        - containerPort: 8080
