apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: redpanda-console
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
