apiVersion: v1
kind: Service
metadata:
  name: kafka-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: kafka-proxy
  ports:
  - name: kafka-bootstrap
    protocol: TCP
    port: 29094
    targetPort: 29094
  - name: kafka-broker-0
    protocol: TCP
    port: 29095
    targetPort: 29095
  - name: kafka-broker-1
    protocol: TCP
    port: 29096
    targetPort: 29096
  - name: kafka-broker-2
    protocol: TCP
    port: 29097
    targetPort: 29097
